---
Name: myroutes
After: framework/routes 
---
Director:
  rules:
    'inbox' : 'InboxController'
    'inbox//$Action/$ID': 'InboxController'
    'tutor//$Action/$ID': 'TutorController'
    'contact//$Action/$ID': 'TutorController'
    'TutorController' : 'TutorController'